# docker-compose

version: "3.8"

services:
  locadoraveiculo.test:
    container_name: locadora-app
    build:
      args:
        user: jaime
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: jaimevalasek/locadora
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks: 
      - docker-locadora
  
  # nginx
  nginx:
      container_name: locadora-nginx
      image: nginx:alpine
      restart: unless-stopped
      ports: 
          - "8800:80"
      volumes: 
          - ./:/var/www
          - ./docker/nginx/:/etc/nginx/conf.d/
      networks: 
          - docker-locadora

  # db mysql
  mysql:
      container_name: locadora-mysql
      image: mysql:5.7.39
      #restart: unless-stopped
      environment: 
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          #MYSQL_ROOT_HOST: "%"
          MYSQL_USER: '${DB_USERNAME}'
      volumes: 
        - ./.docker/mysql/dbdata:/var/lib/mysql
      ports: 
        - "3307:3306"
      networks: 
        - docker-locadora

networks:
    docker-locadora:
        driver: bridge